baseURL = "https://www.tmwhere.com/"
languageCode = "en-us"
title = "tmwhere"
theme = "tmwhere"
disableHugoGeneratorInject = true
disableKinds = ["RSS"]
[menus]
  [[menus.main]]
    name = 'projects'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'posts'
    pageRef = '/posts/'
    weight = 20
  [[menus.main]]
    name = 'links'
    pageRef = '/links/'
    weight = 30
