baseURL = "https://www.tmwhere.com/"
languageCode = "en-us"
title = "tmwhere"
theme = "tmwhere"
disableHugoGeneratorInject = true
disableKinds = ["RSS"]
[menus]
  [[menus.main]]
    name = 'Projects'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
